PyCQA/bandit

- .github/issue_template.md
- bandit/cli/main.py
This patch adds a template for Issues opened against the Bandit
project. That way, minimum information is present to debug the
problem.
> Create an issue template for the project

- README.rst
This includes a pretty icon badge to the README showing the current
build status for bandit on brach master from Travis CI.
> Add a build status badge to the README

- README.rst
- setup.cfg
Now that Travis CI is testing Bandit on Python 3.6, the metadata
classifier of setup.cfg should declare this.
> Show support for Python 3.6

- README.rst
Commit dc3ff2d91785eee49394bd7c8b9e75ddfb616ea4 introduced new
blacklist check of import_pycrypto, but didn't include this in
the README.
This trivial patch updates the README with the new blacklist import
check.
> Add missing B413 import_pycrypto in README

- setup.cfg
Bandit should reference bandit.readthedocs.io for the home-page
instead of a main PyCQA link. That way those seeing Bandit on PyPI
will be properly navigated to the Bandit documentation.
> Use bandit.readthedocs.io in setup.cfg

- doc/source/plugins/b703_django_mark_safe.rst
PR #295 added a new plugin to check for django XSS, but forgot
a link to the plugin documentation. This patch adds just that.
> Add missing documentation link for B703

- .travis.yml
Currently Travis-CI is only running tox with venv for py27,py35,py36,
and pypy. But the venv for pylint and pep8 are defined in tox and
should be run also.
> Enable travis to run pylint and pep8 tox env

- setup.cfg
The development status classifier denotes the development status
of the project. Bandit should be considered a mature stable project
by now.
Fixes Issue #320
> Add development status classifier

- README.rst
- bandit/blacklists/calls.py
- examples/tempnam.py
- tests/functional/test_functional.py
Crikey, it's been a while...
This adds os.tempnam() / os.tmpnam() to the calls blacklist.
Per https://docs.python.org/2.7/library/os.html#os.tempnam and https://bugs.python.org/issue17880, this was left in 2.7 for legacy reasons, but use is potentially dangerous and tmpfile() is recommended instead.
> add os.tempnam() / os.tmpnam() to blacklist

- bandit/plugins/insecure_ssl_tls.py
A few of the plugins used :doc: docstring tag to refer to another
doc. This doc style doesn't render properly when viewing the docs.
For example, take a look here:
https://bandit.readthedocs.io/en/latest/plugins/b502_ssl_with_bad_version.html#b502-ssl-with-bad-version
To fix this, I simply moved the link to the :seealso: block and
reference the other function using the :func: tag.
> Repair some broken see also links in the doc

- bandit/formatters/xml.py
- tests/unit/formatters/test_xml.py
Outputting bandit report as XML does not put `more_info` URL while it
would if the output format is YAML or JSON. This patch set adds the
`more_info` URL to the XML display.
Signed-off-by: Tin Lam <tin@irrational.io>
> Add more_info URL to XML output

- bandit/blacklists/calls.py
- bandit/blacklists/imports.py
- examples/dill.py
- tests/functional/test_functional.py
Dill is a wrapper around pickle and thus is vulnerable to the same
threat. Dill documentation states that dill "is not intended to be secure
against erroneously or maliciously constructed data. It is left to the
user to decide whether the data they unpickle is from a trustworthy
source." (https://pypi.org/project/dill/)
> Report dill usage

- .travis.yml
- bandit/formatters/html.py
This patch adds the prerelease version of Python 3.8 to the testing.
Although Bandit is unlikely to have compile errors with any future
version, this step allows us to get a head start on any that may
arise.
> Add experimental Python 3.8-dev to test with

- bandit/formatters/text.py
- tests/unit/formatters/test_text.py
Outputting bandit report as text does not put `more_info` URL while it
would if the output format is YAML or JSON. This patch set adds the
`more_info` URL to the text display.
Signed-off-by: Tin Lam <tin@irrational.io>
> Add more_info URL to text output

- bandit/formatters/screen.py
- tests/unit/formatters/test_screen.py
Patch set adds more_info URL to the screen formatter.
Partially-Closes: #323
Signed-off-by: Tin Lam <tin@irrational.io>
> Add more_info URL to screen formatter

- bandit/formatters/csv.py
- tests/unit/formatters/test_csv.py
Patch set adds more_info URL to the csv formatter.
Closes: #323
Signed-off-by: Tin Lam <tin@irrational.io>
> Add more_info URL to csv formatter

- bandit/formatters/yaml.py
- bandit/plugins/django_sql_injection.py
- bandit/plugins/django_xss.py
There have been significant changes since the 1.4.0 release, so
I'd like the next release to be 1.5.0 instead of 1.4.1. This patch
replaces 1.4.1 references with 1.5.0.
> Change ver 1.4.1 references to 1.5.0

- README.rst
- bandit/plugins/ssh_no_host_key_verification.py
- doc/source/plugins/b507_ssh_no_host_key_verification.rst
- examples/no_host_key_verification.py
- setup.cfg
- tests/functional/test_functional.py
This new plugin adds a check that detects whether some code using
paramiko is ignoring the host key verification.  Ignoring a host
key is the equivalent of ignoring a certificate as part of the
TLS protocol.
Original author: Eric Brown <browne@vmware.com>
Fixes Issue: #357
> New plugin to check for ignoring host keys

- examples/imports-with-importlib.py
Follow up for #369, instead of adding a specific no-op test case, just add the relevant input on the existing one as in _weak_cryptographic_key_sizes.py_.
Signed-off-by: Antoine Salon <asalon@vmware.com>
> Adding test case for traversal crash

- README.rst
- bandit/cli/main.py
- bandit/core/manager.py
- bandit/formatters/screen.py
- bandit/formatters/text.py
- doc/source/man/bandit.rst
- tests/unit/cli/test_main.py
This commit adds a new command line argument to hide output
when the result of the scan is passing with no warning/errors.
The new option is -q or --quiet. It also allows --silent to be
consistent with the GNU standard on CLI options [1].
[1] http://www.gnu.org/prep/standards/html_node/Option-Table.html#Option-Table
Fixes Issue #384
> Add option -q, --quiet, --silent to hide output

- pylintrc
The pylint config for the project is skipping the check of R0204,
but there are no occurances of this warning in the code.
> No need to skip R0204: redefined-variable-type

- .travis.yml
Since Python 3.8 is going through significant changes, we should
allow failures and not block other commits from merging because
of 3.8 compatibility.
> Allow failures on dev branch of Python 3.8

- bandit/cli/baseline.py
- bandit/cli/main.py
- bandit/core/manager.py
- bandit/core/metrics.py
- bandit/core/test_set.py
- bandit/formatters/screen.py
- bandit/formatters/text.py
- pylintrc
This patch removes the skipping of pylint check W0612: unused-variable.
Unused variables are replaced with _.
> Fix Pylint warning W0612: use of unused variables

- .pre-commit-hooks.yaml
- README.rst
Resolving: https://github.com/PyCQA/bandit/issues/410
> Add pre-commit config

- README.rst
The recent commit 8f4c216a91d38122228c0cb497f01a9d3dfbd9c8 to
add a pre-commit config includes a link in the README to an install
location.  A minor issue with the link is that it contains a trailing
')' which breaks the anchor location.
> Remove unneeded trailing paren in link

- bandit/formatters/screen.py
- tests/unit/formatters/test_screen.py
The More Info line is something newly introduced for the screen
formatter. The coloring of these lines work by adding a color
marker at the bbeginning and end of the multiline block.  So the
block just needed to be extended by one.
Fixes #407
> Fix more info line to be in color also

- bandit/formatters/screen.py
- requirements.txt
Currently, text colors do not render if using `bandit` in a Windows terminal interface (both PowerShell and CMD).
Example: 
This PR resolves that issue by patching stdout using `colorama` when running on Windows. Colorama will intercept any ANSI escape codes and convert them to the proper Windows console API calls to change text color (as far as I understand it at least, I'm not a colorama developer). 
Example with the fix applied:
Caveats: this adds a dependency on `colorama` for Windows. It is a very common dependency for Windows Python programs with a CLI interface, is actively maintained, and is licensed under BSD-3.
> Fix terminal colors not displaying properly on Windows

- bandit/plugins/injection_sql.py
- examples/sql_statements-py36.py
- tests/functional/test_functional.py
- added check for f-string sql injection
- added test
> [Fix for PyCQA#427]

- bandit/plugins/injection_paramiko.py
- examples/paramiko_injection.py
- tests/functional/test_functional.py
Paramiko's invoke_shell function does not take a command argument
even though the Bandit example implied that. It simply opens a stream
for communicating with a shell. Therefore, it should not be flagged
as part of the Bandit scan.
The current example of paramiko command injection does not properly
create an instance of the SSHClient before calling the functions
on the client. Instead it's calling the functions statically which
is not proper syntax.
This patches updates the plugin and example. Bandit, however, is
still functioning properly to detect the improper use of exec_command().
Fixes Issue #375
>  Remove paramiko invoke_shell and fix example

- bandit/plugins/yaml_load.py
- examples/yaml_load.py
PyYAML also supports `CSafeLoader`. This is used for faster loading, if you have the right libraries installed. This check should not alert off this loader, because it is still safe (just faster).
While I was at it, I also did a bit of minor refactoring, to reduce the number of indents used.
> Supporting CSafeLoader in yaml.load plugin

- bandit/core/manager.py
- examples/nosec.py
- pylintrc
- tests/functional/test_functional.py
- tests/functional/test_runtime.py
The string "# nosec" has a chance (albeit remote) that it can be
part of the code on the line not just within the comment. Bandit
currently checks the entire line for that string.
This patch tokenizes the line of input to figure out what piece
is a comment, then compares whether that comment contains "# nosec".
Fixes #383
> Properly handle nosec strings in code

- bandit/core/config.py
- examples/hardcoded-tmp.py
- tests/unit/core/test_manager.py
- tests/unit/core/test_util.py
- tests/unit/formatters/test_csv.py
- tests/unit/formatters/test_html.py
- tests/unit/formatters/test_json.py
- tests/unit/formatters/test_screen.py
- tests/unit/formatters/test_text.py
- tests/unit/formatters/test_xml.py
- tests/unit/formatters/test_yaml.py
Also uniformize the usage of the `with` context manager to prevent resource leaks.
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>
> Fix ResourceWarning: unclosed file

- README.rst
- bandit/blacklists/calls.py
- bandit/core/constants.py
- bandit/plugins/asserts.py
- bandit/plugins/exec.py
- bandit/plugins/injection_shell.py
- doc/source/man/bandit.rst
The python 2 links are kept when in make sense.
> Update python documentation links for version 3 counterparts

- README.rst
- bandit/blacklists/calls.py
- bandit/core/constants.py
- bandit/plugins/asserts.py
- bandit/plugins/exec.py
- bandit/plugins/injection_shell.py
- doc/source/man/bandit.rst
Reverts PyCQA/bandit#456
Reverting since the unit tests were not passing.  The README and man page do not match and there is a explicit test to ensure they always do.
> Revert "Update python documentation links for version 3 counterparts"

- bandit/core/manager.py
- tests/unit/core/test_manager.py
Fixes #488 
I've added a test to make sure that both wildcard directory exclusion and the `1.5.1` version of directory exclusion work.
> add test for regression and fix directory exclusion without wildcards

- README.rst
This PR fix the documentation file `README.rst`, Vulnerability Tests from this issue #526
and correct the Formatters arguments on Extending Bandit section.
> fix the documentation file README.rst 

- bandit/cli/main.py
- tests/unit/cli/test_main.py
There are some comments that are not true after recent merge of #510. This PR aim is to fix/remove them.
> Cleanup comments after #510

- .travis.yml
cf. https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
modified:   .travis.yml
> Remove obsolete "sudo" keyword.

- bindep.txt
This is another file leftover from the OpenStack ecosystem. No
need for it now.
> Remove unused bindep.txt file

- bandit/blacklists/calls.py
- bandit/blacklists/imports.py
- examples/shelve_open.py
- tests/functional/test_functional.py
shelve is a stdlib module that wraps pickle in a dict-like interface.
> Add shelve to the pickle blacklists

- README.rst
Fix readme file on Extending Bandit on list things; 
manager, fileobj, sev_level, conf_level, lines=-1
they were not listed on Markdown format
> Fix readme file on Extending Bandit on list things

- .travis.yml
- setup.cfg
Now that Python 3.8 is released and Bandit is fully tested against
it, we can officially claim support of it.
https://www.python.org/downloads/release/python-380/
> Add official support of Python 3.8

- bandit/core/extension_loader.py
- bandit/plugins/django_sql_injection.py
- bandit/plugins/django_xss.py
- doc/source/plugins/b610_django_extra_used.rst
- doc/source/plugins/b611_django_rawsql_used.rst
- doc/source/plugins/b703_django_mark_safe.rst
This fixes broken links in the rst files that were causing docs not to appear in the HTML (fixes #486).
> Fix docs for B610,B611,B703

- doc/source/config.rst
> Add a section explaining "nosec"

- README.rst
- bandit/cli/main.py
- bandit/core/constants.py
- doc/source/man/bandit.rst
This fix follows the example of flake8 in that it sets a default
list of common directories and filename patterns to exclude.
Fixes #543
>  Ignore common directories by default

- .github/workflows/pythonpackage.yml
It appears that Actions are not triggered for all pull requests.
I suspect the Actions need to register for event push and pull_request
in order to run CI on commits.
> Add push and pull request to GH Action trigger

- CONTRIBUTING.md
- README.rst
I've added a `contributing.md` file To help out other users contribute to the project and 
Improve the [community profile](https://help.github.com/en/github/building-a-strong-community/about-community-profiles-for-public-repositories)
This closes: https://github.com/PyCQA/bandit/issues/548
> Add contributing file

- README.rst
In python3 there is no `virtualenv`. python2 is EOL. The venv directive should consider python3 first.
> [DOC] Support python3 venv creation

- CONTRIBUTING.md
The newly introduced contributing guide has several typos and
incorrect statements that should be fixed up.
> Cleanup some typos in recent contributor guide

- bandit/formatters/screen.py
Fixes #580.
This makes sure `colorama` is properly disabled.
> Fix colorama not being disabled after being used

- bandit/plugins/django_xss.py
Fix NoneType exception when `with` statement don't contains `as`
> Resolve 'NoneType' object has no attribute 'id'Traceback in django_mark_safe

- bandit/plugins/app_debug.py
- bandit/plugins/general_bad_file_permissions.py
- bandit/plugins/general_hardcoded_tmp.py
- bandit/plugins/injection_shell.py
- bandit/plugins/injection_sql.py
Move `# noqa` from inside docstrings to the end of the docstring. This avoids rendering the **# noqa** tag in the documentation as reported in #644 while preventing flagging the excessive line lengths in the linting.
Note: I also added the `E501` label to maintain the original intent of applying the `# noqa` tag to the long lines only.
Fixes #644.
> Fix # noqa rendering in docs

- bandit/core/manager.py
> Don't show progress information on --quiet

- bandit/core/context.py
- bandit/plugins/asserts.py
- tests/functional/test_functional.py
- tests/unit/core/test_context.py
Adding this configuration allows the user to skip the assert_used check
against some files. This is useful because asserts are very common
in test files when using pytest.
Specifying this configuration:
```
assert_used:
skips: ['test.py$', '^test']
```
would skip all asserts against a test file.
Resolves #346
Thank you for the awesome project and your time!
> Add skip configuration to assert_used

- .github/workflows/publish-to-test-pypi.yml
This action runs on a manual workflow dispatch that can be manually
triggered from the UI. It only publishes to Test PyPI for now.
> GitHub Action to publish to Test PyPI

- .github/workflows/publish-to-pypi.yml
Along with the existing workflow that can publish to
Test PyPI, this change also adds official PyPI.
The difference is that this workflow will only publish
if the commit is tagged.
> Add workflow to publish to PyPI

- README.rst
We no longer use Travis CI, so we shouldn't be using it's badge. This
change switches to the GitHub Action badge.
> Use GitHub Action badge for build

- setup.cfg
Now that Bandit is Py3 only, it should be considered a "Pure-Python
Wheel" instead of a "Universal". Further information can be found
here: https://realpython.com/python-wheels/#specifying-a-universal-wheel
Fixes #654
> Remove universal support on the wheel

- .pre-commit-hooks.yaml
Since b78c938c0bd03d201932570f5e054261e10c5750, the project no longer
supports Python 2.
pre-commit will use the system Python by default. On some systems, this
could be Python 2. To avoid Python 2 usage, specify pre-commit always
uses Python 3.
Without this configuration, some projects have been forced to manually
override this option.
pre-commit docs:
https://pre-commit.com/#overriding-language-version
> Specify language_version in .pre-commit-hooks.yaml

- bandit/blacklists/imports.py
This change modifies the warning using subprocess module. The
module is subprocess, and anything else is a submodule or function.
Fixes #666
> Clearer message for subprocess module use

- bandit/formatters/csv.py
- bandit/formatters/screen.py
- bandit/formatters/text.py
- tests/unit/formatters/test_screen.py
- tests/unit/formatters/test_text.py
Recently, #618 introduced column offsets to the custom formatter.
But other formatters should also show the column offset.
> Show column offset on all formatters

- tests/functional/test_functional.py
* Avoid multiple lines when possible
* Avoid creating variables for single use
> Small syntax and formatting cleanup

- bandit/__init__.py
- bandit/core/__init__.py
- setup.py
The preferred format for license headers in source files is to
use the SPDX short hand form.
> More cleanup of license headers

- bandit/plugins/app_debug.py
- bandit/plugins/injection_wildcard.py
- bandit/plugins/insecure_ssl_tls.py
- bandit/plugins/jinja2_templates.py
- bandit/plugins/mako_templates.py
- bandit/plugins/weak_cryptographic_key.py
- bandit/plugins/yaml_load.py
* Update any reference to a http URL to https for security sake
* Update any invalid links also
* Remove links not applicable
> Replace http with https URLs

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
GitHub finally supports the ability to automatically default to a label given in the template.  This will save on manually assigning labels from now on.
> Add default labels to issues

- bandit/formatters/html.py
- tests/unit/formatters/test_html.py
This commit is to include the line number of a given occurrence when using HTML output format.
Resolves: #672
> Include the line number when using HTML output format

- bandit/cli/main.py
Adds two new command line arguments which allow the user to specify
severity level and confidence level with a key-value pair rather than
repeating a flag. This makes it easier to specify those values if using
an alternate interface which invokes Bandit's CLI. The previous
repeatable flags have been retained and existing workflows will not be
affected.
New arguments:
* --severity-level: Takes an integer from 1 to 4 to set the level (1
for undefined, 2 for low, 3 for medium, 4 for high). This has the same
effect as the existing -l/--level option. If both options are specified,
an error will be printed.
* --confidence-level: Takes an integer from 1 to 4 to set the level (1
for undefined, 2 for low, 3 for medium, 4 for high). This has the same
effect as the existing -i/--confidence option. …
> Add numeric options for severity and confidence

- bandit/core/blacklisting.py
- examples/imports-with-importlib.py
- tests/functional/test_functional.py
This PR fixes the issue when importlib is being used with named arguments outlined in the #694. 
Following cases are found:
1. `importlib.import_module("foo", "bar.baz")` results in `call_args = ["foo", "bar.baz"]` and `call_keywords = {}`
2. `importlib.import_module("foo", package="bar.baz")` results in `call_args = ["foo"]`  and `call_keywords = {"package": "bar.baz"}`
3. `importlib.import_module(name="foo", package="bar.baz")` results in `call_args = []`  and `call_keywords = {"name": "foo", "package": "bar.baz"}`
The simplest approach is to use `context.call_args_count` and if the call_args_count is larger than 0, call `call_args[0]` which will choose `foo`. If call_args_count is equal to 0 then we need to choose `name` from the call_keywords.
I haven't found previous tests covering …
> #694 Bandit fails when using importlib with named arguments

- setup.cfg
This PR adds the license name to the package installation metadata so it can be checked automatically with [`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html). We automatically check the license of all our dependencies this way, and bandit currently fails since it returns "UNKNOWN".
> Add license to package installation metadata

- bandit/blacklists/calls.py
- examples/random_module.py
- tests/functional/test_functional.py
Because [`random.choices()`](https://docs.python.org/3/library/random.html#random.choices) wasn't explicitly listed in the "don't use this" list, I initially thought it was safer version of `random.choice()`.
I realized my mistake and used `secret.choice()` eventually, but this PR is to add `random.choices()` to the unsafe list.
> document that random.choices() isn't secure either

- bandit/cli/main.py
- tests/unit/cli/test_main.py
Previously bandit was not able to read initialization values from the **.bandit** file
like the `exclude` keyword. This has caused a lot of CI pipelines that were using
bandit to fail. In this pull, I have tried to fix this problem.
The CLI of bandit is written with python's popular library `argparse` .
The main problem was with the handling of default arguments' values
of the **bandit** command-line program. The program was not able to
distinguish between manually passed arguments and default arguments
values. Before In the first line of `_log_option_source` function in
`bandit.cli.main.py`, the function only checked whether `arg_val` exists
or not. At first glance, it seems that this is a correct action, but the truth is
that this function fails when the default value of an argument is …
> fix reading initial values from .bandit

- tests/functional/test_runtime.py
$ python --version
Python 3.9.2
```$ bandit -h
usage: bandit [-h] [-r] [-a {file,vuln}] [-n CONTEXT_LINES] [-c CONFIG_FILE] [-p PROFILE] [-t TESTS] [-s SKIPS] [-l] [-i] [-f {csv,custom,html,json,screen,txt,xml,yaml}] [--msg-template MSG_TEMPLATE] [-o [OUTPUT_FILE]] [-v] [-d] [-q]
[--ignore-nosec] [-x EXCLUDED_PATHS] [-b BASELINE] [--ini INI_PATH] [--exit-zero] [--version]
[targets ...]
Bandit - a Python source code security analyzer
positional arguments:
targets               source file(s) or directory(s) to be tested
optional arguments:
-h, --help            show this help message and exit
-r, --recursive       find and process files in subdirectories
(...)
```
$ python --version
Python 3.10.0
```$ bandit -h
usage: bandit [-h] [-r] [-a {file,vuln}] [-n CONTEXT_LINES] [-c CONFIG_FILE] …
```
> test_help_arg: remove assert on 'optional arguments'

- CONTRIBUTING.md
- README.rst
- setup.cfg
- tox.ini
Python 3.5 hit the end-of-life on Sept 13, 2020. As a result,
Bandit should also drop support for it.
> Drop end-of-life Python 3.5

- .github/workflows/pythonpackage.yml
- setup.cfg
- setup.py
- tox.ini
Python 3.6 hit the end-of-life on Dec 23, 2021. As a result,
Bandit should also drop support for it.
> Drop end-of-life Python 3.6

- bandit/core/config.py
We only want to rely on toml when it's present and tell the user how to
resolve things if in fact they want to use toml
Closes #779
> Rely on toml conditionally

- .github/ISSUE_TEMPLATE/bug-report.yml
When opening an issue, the template only allows selecting versions
1.7.0 as the max. The python version is also limited to 3.9.
This change adds the recent Bandit versions of 1.7.1 and 1.7.2, and Python
version of 3.10
> Update issue template with latest versions

- .github/workflows/publish-to-test-pypi.yml
Avoid using master version of gh-action-pypi-publish. Some orgs such as PyCQA don't permit using
a non-released version of an Action. It's also not recommended by GitHub to use unreleased versions
of actions.
Fixes Issue #782
> Use released version of gh-action-pypi-publish

- setup.cfg
This change fixes the use of certain keywords in the setup.cfg
file. Substitutes '-' for '_'
Fixes: #792
> Fix up warnings in output of tox

- bandit/core/metrics.py
The metrics in the output was displaying counts as floats instead
of integers. For example, 15.0 instead of 15. This is due to a
divide call using '/' instead of '//' which rounds down the answer.
We shouldn't have fractional number results anyway since the counts
are always divisible by the rank values.
> Avoid printing metrics as float point numbers

- tests/functional/test_functional.py
This change adds a new functional test of the new snmp plugin
snmp_security_check.
Fixes: #790
> Add functional test of snmp_security_check

- bandit/core/manager.py
- bandit/core/metrics.py
- bandit/core/node_visitor.py
- bandit/core/tester.py
- bandit/formatters/text.py
- doc/source/config.rst
- examples/nosec.py
- tests/functional/test_functional.py
- tests/unit/formatters/test_text.py
This PR allows for disabling specific tests by ID (e.g. B602, B607). It also supports using test name (e.g. subprocess_popen_with_shell_equals_true) as requested in #418 .
the nosec comment behaves nicely with others and can be present anywhere in a string of comments.
If nosec is used without specific tests, it acts as it did before by blanket ignoring all tests for that line.
If nosec is used with specific tests and a test not indicated in the comments is triggered, the line will be caught and reported.
> Disable individual tests

- bandit/plugins/hashlib_new_insecure_functions.py
- examples/hashlib_new_insecure_functions.py
- tests/functional/test_functional.py
In Python 3.9+ hashlib has a new argument named usedforsecurity
to indicate whether the hash is intended to be used for security
or not. The default value is True. So a user must explicit set
to False to state their non-security use.
As a result of this chnage in Python, the severity has been
moved up to HIGH if the usedforsecurity is True. But on earlier
versions of Python, the severity will remain at MEDIUM since
we don't know the intent of usage.
https://docs.python.org/3/library/hashlib.html#hashlib.new
Closes #748
> Check value of usedforsecurity for hashlib

- bandit/blacklists/imports.py
- examples/pyghmi.py
- tests/functional/test_functional.py
Merge branch 'feat/pyghmi' of ssh://github.com/stannum-l/bandit into ipmi
This patch set adds a new bandit plugin to check the use of pyghmi.
Closes #356
Signed-off-by: Tin Lam tin@irrational.io
>  Add new plugin to check use of pyghmi

- CONTRIBUTING.md
- README.rst
- bandit/core/manager.py
- doc/requirements.txt
- doc/source/conf.py
The primary branch name has been renamed from master to main.
As a result of this, some references in the docs must also be
renamed so links are preserved.
> Fix references to the default branch name

- README.rst
There's duplicate information in the README regarding where to contribute,
where to open bugs, where the documentation lies. This change deletes the
dups and also puts the references at the end which is standard for most
documents.
> Cleanup the README

- bandit/cli/main.py
- tests/functional/test_runtime.py
The current behavior is to display an error when no arguments are
given that no files were found. This is a non-standard way for
a command line.
Rather than an error message, no arguments should display the
usage of the command itself.
Partially fixes #678
> Show usage with no arguments

- bandit/cli/main.py
- bandit/core/manager.py
According to command line standards [1], a command line should
do its best to honor certain environment variables requesting
whether color should be part of the standard output. Two such
vars include NO_COLOR (if set) and TERM (if set to dumb), when
set tell the CLI to disable color.
[1] https://clig.dev/#output
Partially-fixes #678
> Respect color environment variables if set

- .github/workflows/pythonpackage.yml
This adds GitHub Action testing on the various operating systems
we can potentially support. At the moment that includes Linux,
macOS, and Windows.
> Test on operating systems we can support

- bandit/plugins/app_debug.py
- bandit/plugins/snmp_security_check.py
- bandit/plugins/yaml_load.py
* Some lines missing code-block
* Missing blank lines for spacing
> Fix up some warnings and errors in docs

- doc/source/conf.py
The readthedocs is using Sphinx 1.8.6 which still uses the
legacy term master_doc for the root toctree.
> Fix root doc for readthedocs

- bandit/core/docs_utils.py
- setup.cfg
- tests/unit/core/test_docs_util.py
In the report of a Bandit run, there are links to the docs as
part of the more information. Today, these links are always
to the latest docs. So depending on the version of Bandit you're
running, these links could contain inaccurate information for
that version.
That's why this change makes it so a specific version of Bandit
is pinned to refer to a specific version of documentation.
> Use versioned links to docs

- bandit/formatters/html.py
The CWE link is currently output in plain text. Given this is an
HTML outoput formatter, it's only natural to use reference link.
> Use CWE link in HTML formatter

- bandit/plugins/hashlib_insecure_functions.py
The hashlib function does not actually check for md2 as the docs
and message claims. Besides, md2 is a very old hash not found in
any Python 3.x version we support.
> Inaccurate message in hashlib check

- .pre-commit-config.yaml
Support for Python 3.6 has been removed in https://github.com/PyCQA/bandit/pull/777, so it looks like pre-commit hooks could get updated to target Python >= 3.7 instead of 3.6.
> Target Python >= 3.7 in pre-commit hooks

- README.rst
Minor nit change to center the logo in the readme for more visual
appeal.
> Center the bandit logo in readme

- README.rst
A recent change to center the logo made use of the html raw keyword
in the README. Apparently this fails when building the Bandit artifact.
```
Checking dist/bandit-1.7.3.dev33-py3-none-any.whl: FAILED
`long_description` has syntax errors in markup and would not be rendered on PyPI.
line 1: Warning: "raw" directive disabled.
warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
```
This change reverts the centering, but keeps the updated link.
> Build of artifact fails if raw directive used

- bandit/plugins/hashlib_insecure_functions.py
This check should not raise an exception if there are no keywords
defined for the call. Makes use of dict get() for safety.
Closes #832
> Fix traceback in hashlib_insecure_functions

- .github/ISSUE_TEMPLATE/bug-report.yml
Add an option for newly released version 1.7.3 for the user to report a bug on.
> Add version 1.7.3 to dropdown

- bandit/core/config.py
Fixes the following error:
Traceback (most recent call last):
File "bin/bandit", line 8, in <module>
sys.exit(main())
File "lib/python3.10/site-packages/bandit/cli/main.py", line 455, in main
b_conf = b_config.BanditConfig(config_file=args.config_file)
File "lib/python3.10/site-packages/bandit/core/config.py", line 45, in __init__
raise utils.ConfigError(
TypeError: ConfigError.__init__() missing 1 required positional argument: 'config_file'
> core/config: Fix ConfigError missing argument if toml is missing

- .github/ISSUE_TEMPLATE/bug-report.yml
Add an option for version 1.7.4 in the bug report in preparation for a new release of 1.7.4 afterwards.
> Add 1.7.4 in issue template

- bandit/plugins/hashlib_insecure_functions.py
Small change to have a variable that has the set of weak hashes.
> Use a constant for weak hashes

- bandit/formatters/screen.py
- bandit/formatters/text.py
- tests/unit/formatters/test_screen.py
- tests/unit/formatters/test_text.py
Currently for the screen and text formatters there is a More Info
line in between the Location line and the code snippet lines.
This change puts the Location with the code snippet as a more
logical grouping of code location information.
> Group location line with code output

- bandit/core/node_visitor.py
- bandit/core/utils.py
- examples/multiline_statement.py
- tests/functional/test_functional.py
Python 3.8 and above have new ast node attributes to identify the
end line number and end column offset [1].
Python 3.8 also fixes line numbers for multiline strings [2].
This fixes the issue mentioned in #820, but only for Python 3.8+.
[1] https://docs.python.org/3.8/library/ast.html#ast.AST.end_lineno
[2] https://bugs.python.org/issue31241
> Fix line range using Python 3.8 end_lineno

- bandit/blacklists/calls.py
- examples/httplib_https.py
- tests/functional/test_functional.py
This check existed because of insufficient checking of certificates
when using httpsconnection. Since 3.4.3, this has been fixed. And
since Bandit supports 3.7+, there is no longer a need to scan for
this.
Closes #857
> Removal of blacklist call B309 httpsconnection

- bandit/plugins/hashlib_insecure_functions.py
Instead of a message telling the user the possible weak hashlib
functions in use, this change indicates to the user the exact
hash that is being used.
> Indiciate hash type in message

- doc/source/plugins/b324_hashlib.rst
The hashlib_insecure_functions module is missing documentation. More
than likely this is a result of having checks in blacklist for hashlib
and also a plugin. The blacklists have a reserved Id range of 3xx, which
is what this plugin is using.
Near term, this change publishes a page for B324 hashlib plugin. Longer
term, the bandit Id should be migrated out of the 3xx group to something
more appropriate.
Closes #559
> Add doc for hashlib plugin

- bandit/core/constants.py
- bandit/core/manager.py
- requirements.txt
The module rich has an excellent and versatile implementation of a
progress bar for Python code. Bandit has an existing custom progress
indicator.
This change makes use of rich for a more visually pleasing progress
bar and more informational by including metrics.
The down side is that this does add another dependency. But I
think it can be useful in the future when implementing multi-process
processing of source code since rich is well adapted for that.
https://github.com/Textualize/rich
> Make use of rich for progress bar

- bandit/core/config.py
- setup.cfg
- test-requirements.txt
Resolves #828 
Replace `toml` with `tomli` for parsing bandit options defined in `pyproject.toml`.
The reason for requiring at least `1.1.0` is because support for text files has been [deprecated in 1.2.0](https://github.com/hukkin/tomli/blob/d21aa80b441fb46361386c44f92985b4921b9b8b/CHANGELOG.md#120) then [removed in 2.0.0](https://github.com/hukkin/tomli/blob/d21aa80b441fb46361386c44f92985b4921b9b8b/CHANGELOG.md#200), and support for binary files has only been [added in 1.1.0](https://github.com/hukkin/tomli/blob/d21aa80b441fb46361386c44f92985b4921b9b8b/CHANGELOG.md#110), so this ensures that users have `1.1.0+`, to reliably be able to read binary files.
As `tomli` only reads binary files, it is required to open the file using `rb` flags, which also impacts the format passed to …
> Replace `toml` with `tomli`

- doc/source/plugins/b109_password_config_option_not_marked_secret.rst
- doc/source/plugins/b111_execute_with_run_as_root_equals_true.rst
The B109 and B111 plugins were removed in 1.5.0 and the docs only
referenced them for historical information.
This change fixes the titles to be what they were originally and
adds the complete doc and indicates deprecated and removed in
1.5.0.
Closes #367
> Fix up B109 and B111 removed plugins docs

- .pre-commit-config.yaml
This change bumps the version of Black in use to fix the errors
seen coming out of the format build step.
See https://github.com/psf/black/issues/2964
> Fix for build breaks in format job

- doc/source/blacklists/index.rst
- doc/source/formatters/index.rst
- doc/source/plugins/index.rst
We don't need the word "Bandit" prefixed to each of these section
titles:
* Bandit Test Plugins
* Bandit Blacklist Plugins
* Bandit Report Formatters
> Remove redundant word Bandit in titles of sections

- doc/source/index.rst
This change adds a Discord link to our docs in the contributing
section so users know where they can reach out for questions
and discussion.
Closes #775
> Add a Discord link to the docs

- bandit/plugins/logging_config_insecure_listen.py
- doc/source/plugins/b612_logging_config_insecure_listen.rst
- examples/logging_config_insecure_listen.py
- setup.cfg
Hi,
I would like to contribute a plugin based on Python's [security consideration](https://docs.python.org/3/library/logging.config.html#security-considerations) regarding `logging`.
The actual issue (usage of `eval()`) is when `logging.config.fileConfig` is called on an untrusted configuration file. However, it seems very obvious that configuration files are critical for security so will be write-protected to authorised users. The interesting attack vector is possible when an application [exposes socket server](https://docs.python.org/3/library/logging.config.html#logging.config.listen) to listen for configuration file from a network socket that a local attacker can exploit. 
So this plugin checks for usage of `logging.config.listen` without `verify` argument which allows integrity …
> Adding logging.config.listen() plugin with examples

- .github/CODEOWNERS
It seems that ghugo is no longer a valid user on GitHub. Also ghugo hasn't been active
in the Bandit community in a long while. Therefore, this change will remove the user.
Unknown owner on line 1: make sure @ghugo exists and has write access to the repository
> Removal of ghugo

- doc/source/start.rst
The getting started doc informs the user how to install Bandit via pip. However, it gives
instructions to use pip and pip3. Bandit is only supported on Python 3.x now. Also, it's
less common to use pip3 when using convenience modules like pyenv. Therefore, this
change leaves just the pip line.
> Remove redundant pip line

- doc/source/config.rst
- doc/source/start.rst
As mentioned in https://github.com/PyCQA/bandit/issues/606#issuecomment-1077323898 , there are some errors in the configuration documentation.
This has been corrected.
Note that only the documentation has been corrected, not the man page or help messages.
> Corrected documentation on configuration

- .github/workflows/pythonpackage.yml
Python 3.11 is due for release [in October 2022](https://peps.python.org/pep-0664/).
While this is relatively far away from today, it could still be great to start testing against it, especially for testing that `tomllib` from [PEP 680](https://peps.python.org/pep-0680/) is able to parse configuration correctly.
Python 3.11 alpha 7 is the first pre-release version that includes `tomllib`.
> Start testing against Python 3.11

- bandit/formatters/html.py
One line in the `issue_block` template string in `formatters/html.py` is lacking the closing `</b>` tag. As a result, all text after the first occurrence of `CWE:` is bold in the generated HTML report.
Example:
The same example after applying the fix:
> Fix an unclosed <b> tag in HTML formatter

- doc/source/plugins/b612_logging_config_insecure_listen.rst
https://bandit.readthedocs.io/en/latest/plugins/index.html has this typo
> 'Test plugin listing' in docs incorrectly pointing B612 to plugin ref of B102

- examples/yaml_load.py
- tests/functional/test_functional.py
The yaml module supports passing the Loader of choice.
Passing yaml.Loader is considered unsafe. This commit
adds that example and ensures Bandit detects it.
> Add another bad example of yaml load

- doc/source/start.rst
Just a convenience to save someone from finding the repo and tags.
As an alternative, if there's appetite for it, I could rewrite this section. 
- Include a tag in the yaml example.
- Suggest `pre-commit autoupdate --repo "https://github.com/PyCQA/bandit"` which will update the version and install it.
- Remove `pre-commit install suggestion`
> Add releases link in "Version control integration"

- .github/workflows/dependency-review.yml
New major release of this action:
https://github.com/actions/dependency-review-action/releases/tag/v2.0.0
> Update version of dependency-review-action

- bandit/core/manager.py
Only print the message to use "--debug" if debug logging not already
turned on.
Closes #883
> Avoid redundant message if debug on

- examples/hashlib_new_insecure_functions.py
- tests/functional/test_functional.py
* hashlib does not support name as the kwargs argument
* 'string' is not a keyword of kwargs
Fixes #865
> Remove invalid checking on hashlib

- bandit/plugins/weak_cryptographic_key.py
The weak_cryptographic_key plugin is missing some various
elliptical curve types.
> Add some missing curve types

- bandit/cli/main.py
When passing the "number" option from the INI file we did
not take into account to store its value as an integer
(when that value is not None).
Resolves: #922
> Fix reading the number argument from config file

- bandit/plugins/request_without_timeout.py
The see also section refers to an invalid URL. This change updates
with the latest known reference.
> Docs for request without timeout has dead link

- bandit/core/context.py
- bandit/plugins/yaml_load.py
- examples/yaml_load.py
The yaml.load() function has a second argument that is typically
passed as a kwarg. However, someone could pass as a positional
argument as well. In such a case, Bandit would flag code passing
a SafeLoader even though that is validly secure.
The fix involves looking at the positional args. However, the
convenience function to do so also had no handling of ast.Attribute
as args. So get_call_arg_at_position() was modified to function much
like call_args().
Closes #546
> Fix a false positive condition yaml_load

- bandit/plugins/insecure_ssl_tls.py
- examples/ssl-insecure-version.py
- tests/functional/test_functional.py
The IETF officially deprecated TLS 1.1 in March 2021. As such,
Bandit should now check for and warn of its use.
https://datatracker.ietf.org/doc/rfc8996/
> Check for deprecated TLS 1.1

- bandit/plugins/weak_cryptographic_key.py
- examples/weak_cryptographic_key_sizes.py
The weak_cryptographic_key assumes a positional arg when it doesn't
find a value for the keyword arg. The issue is that sometimes the
keyword arg is a ast.Call or other undeterminate values. And as
a result throws a Traceback.
This change will make the plugin a little more robust so it doesn't
throw the Traceback. It won't be able determine the value of the
curve in this case, but can ignore it.
Fixes #545
> weak_cryptographic_key assumes positional arg

- bandit/plugins/exec.py
Bandit no longer supports Python 2, so there is no need
for a plugin to reference exec() in the Py2 docs.
> Remove python 2 reference in docs

- bandit/blacklists/calls.py
- examples/dill.py
- examples/pickle_deserialize.py
- tests/functional/test_functional.py
* cPickle doesn't exist in Python 3+, therefore we can drop
* examples/pickle_deserialize.py uses StringIO.StringIO which was
replaced with io.StringIO. However, these calls expect bytes, not str
* Similarly examples/dill.py using StringIO to be replaced with BytesIO.
It was also using an instance of an non-existant class name of Undillr
and not Unpickler.
> Fixup some invalid pickle testing

- bandit/core/issue.py
- bandit/formatters/json.py
- bandit/formatters/yaml.py
The json and yaml formatters were not outputting the lines of
content according to the user's selection.
This is a result of issue:as_dict() function that does not pass
through the max_lines argument to get_code. As a result, it
would always return the default of 3.
This change now optionally passes through desired lines of content.
Fixes #604
> Fix json and yaml formatters to respect num lines

- doc/source/config.rst
- doc/source/start.rst
As discovered in #488 (latest comments) and reported in #528.
Also attempts to improve the documentation code by aligning code block indenting replacing simple code blocks (`::`) with source code markup code blocks in reStructuredText.
- Despite the name, `exclude_dirs` also recognizes single files, not only directories.
- In the long run it may make sense to consolidate the two options `exclude` and `exclude_dirs`.
> [docs] Mention `exclude_dirs` option available in TOML and YAML

- bandit/formatters/xml.py
- bandit/plugins/exec.py
Follow up to #933 to remove Python 2 code example
> remove py2 exec example in docs

- doc/source/config.rst
Took me a bit and #902 to figure this one out
> DOC: Add explanation on how to use pre-commit with config file

- tox.ini
Version 4 of Tox is currently breaking the build. Therefore, until those issues are fixed, this change can revert to Tox 3.x.
> Fix breaking build due to new tox

- bandit/plugins/injection_sql.py
- examples/sql_multiline_statements.py
- examples/sql_statements.py
- tests/functional/test_functional.py
This commit fixes detecting SQL injection
in statements like:
```
f"SELECT {column_name} FROM foo WHERE id = 1"
f"INSERT INTO {table_name} VALUES (1)"
f"UPDATE {table_name} SET id = 1"
```
Before this change, the bandit was analyzing statements
by parts, especially, in the case of:
`"SELECT {column_name} FROM foo WHERE id = 1"`
it was firstly checking `"SELECT "` for being
an SQL statement and then `" FROM foo WHERE id = 1"`.
Neither of these parts match to defined
regular expressions:
```
r"(select\s.*from\s|"
r"delete\s+from\s|"
r"insert\s+into\s.*values\s|"
r"update\s.*set\s)",
```
Thus SQL injection was not detected.
This commit makes bandit checking the whole SQL
statement for matching the above regexps.
However, since it uses `ast.unparse` it works
only for python >= 3.9.
Resolves: …
> Improve detecting SQL injections in f-strings

- bandit/core/node_visitor.py
- bandit/core/tester.py
- bandit/core/utils.py
- examples/sql_multiline_statements.py
- tests/functional/test_functional.py
This commit improves handling nosecs
in multi-line strings, like:
```
1. nosec_not_working = f"""
2.     SELECT * FROM {table}
3. """  # nosec
```
Before this change, bandit was checking if there is
a nosec in line 1. Now, in the case of ast `Constants`
it searches for nosec in the last line of the expression.
This commit also moves detecting nosec without test number
to test phase from "pre-visit" phase.
It may increase the time of performing checks but avoids
counting the same nosec mark multiple times.
"pre-visit" phase is run separately for each part of multi-line
string split by `FormattedValue` items. Thus for the above example,
it would be run twice, the first time for `"\n    SELECT * FROM "`
and the second time for `"\n"` making the nosec being counted twice.
Resolves: #880
> Improve handling nosec for multi-line strings

- .github/ISSUE_TEMPLATE/bug-report.yml
This is a fix to properly render the 3.10 option in the Python version drop down. Markdown is rendering
3.10 as 3.1.
> Render Python 3.10 in drop down correctly

- bandit/plugins/request_without_timeout.py
- examples/requests-missing-timeout.py
Fixes false postive detecting the usage of the requests module without a timeout. This resolves cases of modules with the word "requests" in the name, but does not match the actual popular third-party module "requests".
The fix checks the fully qualified name and ensures index 0 is "requests". Previously, the code was match any module name with "requests" in it.
Fixes #1010
> Improper detection of non-requests module

- bandit/blacklists/imports.py
- examples/xml_xmlrpc.py
The xmlrpclib of Python 2.x was replaced in Python 3 with xmlrpc [1]. Since Bandit no longer supports Python 2.x, it needs to update to the latest module name.
As indicted in [2], xmlrpc is still not secure against maliciously constructed data.
[1] https://python.readthedocs.io/en/v2.7.2/library/xmlrpclib.html
[2] https://docs.python.org/3/library/xmlrpc.client.html#module-xmlrpc.client
> xmlrpclib replaced with xmlrpc in Python3

- bandit/cli/config_generator.py
- bandit/cli/main.py
- bandit/core/config.py
- bandit/core/context.py
- bandit/core/docs_utils.py
- bandit/core/extension_loader.py
- bandit/core/manager.py
- bandit/core/meta_ast.py
- bandit/core/node_visitor.py
- bandit/core/test_set.py
- bandit/core/tester.py
- bandit/core/utils.py
- bandit/formatters/custom.py
- bandit/formatters/html.py
- bandit/formatters/screen.py
- bandit/formatters/text.py
- bandit/plugins/general_hardcoded_password.py
- bandit/plugins/hashlib_insecure_functions.py
- bandit/plugins/injection_shell.py
- bandit/plugins/injection_wildcard.py
- doc/source/conf.py
- pylintrc
- setup.py
- tests/functional/test_functional.py
- tests/unit/cli/test_baseline.py
- tests/unit/core/test_config.py
- tests/unit/core/test_util.py
- tests/unit/formatters/test_screen.py
- tests/unit/formatters/test_text.py
- converted several format strings to f-strings
- sorted and tidied imports (isort)
- cleaned some whitespace
- updated pylintrc to exclude examples
- updated pylintrc to specify all currently failing cases, so any new ones could be part of pre-commit if so wished
> language and linting updates

- .github/workflows/pythonpackage.yml
All checks in pythonpackage.yml are run by tox. Manual installation of requirements is unnecessary here, as tox will install and run everything in separate virtual environments.
> Skip unnecessary `pip install` commands in the pythonpackage.yml workflow

- .github/workflows/dependency-review.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
- .github/workflows/pythonpackage.yml
Update `actions/dependency-review-action` and `actions/setup-python` used in bandit's Actions workflows.
> Update versions of used GitHub Actions

- .pre-commit-config.yaml
- bandit/cli/baseline.py
- bandit/core/manager.py
- bandit/core/meta_ast.py
- bandit/core/metrics.py
- bandit/formatters/custom.py
- bandit/formatters/json.py
- bandit/formatters/screen.py
- bandit/formatters/text.py
- bandit/formatters/xml.py
- bandit/formatters/yaml.py
- bandit/plugins/injection_shell.py
- tests/functional/test_functional.py
- tests/unit/cli/test_baseline.py
- tests/unit/cli/test_main.py
- tests/unit/core/test_config.py
- tests/unit/core/test_manager.py
- tests/unit/core/test_util.py
- tests/unit/formatters/test_json.py
- tests/unit/formatters/test_xml.py
- tests/unit/formatters/test_yaml.py
This PR is the result of updating all pre-commit hooks and then running the updated hooks on all files.
I pushed this in three separate commits for clarity. Let me know if you want me to squash & force push.
> Update pre-commit hooks

- doc/requirements.txt
- doc/source/conf.py
There is a sphinx extension (sphinx_copybutton) that enables a copy button for every code-block included in our docs. This is a nice and easy usability change.
https://sphinx-copybutton.readthedocs.io/en/latest/
https://github.com/executablebooks/sphinx-copybutton
https://pypi.org/project/sphinx-copybutton/
> Add a copy button to all code snippets in docs

- bandit/__init__.py
- requirements.txt
The importlib module has a metadata.version to retrieve the package version of the given module. This can be used in lieu of pbr for gathering versioning. As a result we can drop the runtime dependency on pbr.
Fixes #839
Fixes #735
> Replace pbr in favor of importlib

- .github/FUNDING.yml
This change adds Python Software Foundation as the link for fiscal sponsorship. Now that Bandit is a member of the fiscal sponsorees, we can accept donations through their channels.
This also means, we need to remove the Open Collective option as it would conflict with PSF.
https://www.python.org/psf/fiscal-sponsorees/
> Switch from open collective to PSF

- .pre-commit-hooks.yaml
I would like you to consider this small change to the pre-commit manifest. 
Currently pre-commit may run Bandit hook with multiple processes, which can lead to Bandit generating multiple reports from these runs. It's only a bit confusing when you run Bandit for the first time on a moderately large database and output report on the screen, but it's much worse if you're saving your report to, let's say, an HTML file. Then you would get a straight wrong report.
This is what happens, when I run the same Bandit command with pre-commit and without it on the same codebase:
**(pre-commit)**
**(w/o pre-commit)**
Each run just overwrites the report file, and in the end we're left with what happens to be the latest run result. 
One can mitigate this problem by using the `-r` flag and setting …
> Make pre-commit run Bandit hook using a single process

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
- .github/workflows/pythonpackage.yml
- .pre-commit-config.yaml
- bandit/core/utils.py
- setup.cfg
- setup.py
- tests/functional/test_functional.py
- tox.ini
Python 3.7 was end-of-life as of 6-27-2023. As such, there is no need for Bandit to continue to support it.
Fixes #992
> Remove support for Python 3.7 due to end-of-life

- bandit/formatters/utils.py
This removes the first condition in the function that seems to be no longer needed as it's specific to Python 2.
> Simplify `wrap_file_object`

- bandit/plugins/django_sql_injection.py
- examples/django_sql_injection_raw.py
- tests/functional/test_functional.py
Fix rule B611: django_rawsql_used breaking when a user passes in keyword arguments to Django's `RawSQL`.
Closes #764
> django_rawsql_used: support keyword arguments used in `RawSQL`

- requirements.txt
Avoid gitpyhon CVE-2022-24439
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24439
> Avoid gitpyhon CVE-2022-24439

- bandit/blacklists/calls.py
- Suggest `secrets` as an alternative to `random`
- Fix typo
Resolves #1023
> Update blacklist call documentation

- bandit/core/config.py
- bandit/core/extension_loader.py
- bandit/core/manager.py
- examples/nosec.py
This extends nosec parsing to enable blacklists to be ignored by their name, not just by id.
There were 2 issues with the previous implementation:
1. The regex did not match numbers, which is needed for some names, such as md5. The code would only match "md" in this case.
2. The function that maps plugin names to ids only considered plugins but not blacklists.
Both of these are now addressed.
Closes #988
> Support ignoring blacklists by name

- .github/dependabot.yml
The dependabot.yml file isn't enabling dependabot checks for some reason. This change updates
the file to match the example given by the GitHub documentation more closely.
I suspect the issue is the swapped keys of `schedule` and `interval`.
This change also modifies the schedule of update checks to weekly instead of monthly.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions
> Fix dependabot to update github actions

- .readthedocs.yaml
The ReadtheDocs build is currently failing because it is unable to find sphinx_copybutton. This occurs because ReadtheDocs by default will only install dependencies of the default requirements.txt at the root.
The fix needs to install the sphinx_copybutton package found in doc/requirements.txt. ReadtheDocsv2 now provides a better configuration using a YAML file [1] instead of just the UI and its limited options.
This change adds the new .readthedocs.yaml file that allows us to control what dependencies are installed via two requirements.txt files, one in root and one in doc/.
[1] https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
> Fix for ReadtheDocs build

- bandit/plugins/ssh_no_host_key_verification.py
- examples/no_host_key_verification.py
- tests/functional/test_functional.py
`paramiko` supports passing both a class and a class instance for the policy in `set_missing_host_key_policy`
(https://github.com/paramiko/paramiko/blob/8e389c77660c5cdae3069b478665427d23012853/paramiko/client.py#L171-L191). This updates B507 to account for both styles.
> fix(plugins/B507): also detect class instances

- .pre-commit-config.yaml
The docs of `black` recommends using a special mirror repository for the pre-commit hook.
More info:
https://black.readthedocs.io/en/stable/integrations/source_version_control.html#version-control-integration
https://github.com/psf/black/blob/main/CHANGES.md#integrations-3
> Use mirror repository for black pre-commit hook

- bandit/core/config.py
This is a naive fix for bandit crashing when it encounters a `pyproject.toml` which does not contain any specific bandit configuration.
This resolves the common failure mode that is seen, but does not cause bandit to fall back to another configuration source if the `pyproject.toml` does not contain any `tool.bandit` block.
Resolves #1027
> Fix crash on pyproject.toml without bandit config

- bandit/plugins/ssh_no_host_key_verification.py
- examples/no_host_key_verification.py
- tests/functional/test_functional.py
Paramiko permits various ways of importing the missing host key policy. It allows paramiko.client.AutoAddPolicy or paramiko.AutoAddPolicy. The later isn't being handled in Bandit.
This change adds news tests and modifies the plugin to inspect the AST to determine whether the argument is an Attribute, Name, or Call.
Fixes #1077
> Handle variant in how policy is passed in paramiko

- bandit/plugins/injection_sql.py
- examples/sql_statements.py
- tests/functional/test_functional.py
This extends the existing implementation for detecting possible cases of SQL injection to account for `str.replace` used in the string construction.
Use of `str.replace` can lead to SQL injection in much the same way as `str.format` can, and that is already considered in the pre-existing implementation, along with other common string constructions.
Resolves #878
> Flag str.replace as possible sql injection

- bandit/blacklists/imports.py
The module name described in the warning message is incomplete and confusing.
> defusedxml: Show correct module name

- .github/FUNDING.yml
Now that Tidelift is officially lifting Bandit, we should include it in our sponsor links.
> Add tidelift to the sponsor funding list

- bandit/cli/baseline.py
- bandit/core/utils.py
- bandit/formatters/xml.py
- bandit/plugins/general_bind_all_interfaces.py
- bandit/plugins/general_hardcoded_tmp.py
* Used nosec for false various positives
* Switched to usage of defusedxml
* Fixed the empty try-except-pass to have code in the except block.
Fixes #948
> Fix up issues found running Bandit on itself

- bandit/blacklists/calls.py
- examples/random_module.py
- tests/functional/test_functional.py
In Python 3.9, the random module added new function randbytes(n). This function shouldn't be used for any cryptographic operations. As the doc recommends, use secrets.token_bytes() instead.
https://docs.python.org/3/library/random.html#random.randbytes
> Add random.randbytes to blacklist calls

- bandit/core/manager.py
- tests/unit/core/test_manager.py
The get_module_qualname_from_path() function called by the node visistor expects that all files are explicitly named with a "head" and "tail" which are path delimiters to denote where the file is within a python project.
However, if someone uses the command line and simply asks bandit to scan dummy.py in the current working directory, it will be missing the explicit "./" prefix in order for get_module_qualname_from_path to run and determine the module fully qualified name from the path.
So this fix simply prepends a dot and delimiter to explicitly denote a file in the current working directory as given from the CLI.
Fixes #907
> Prepend ./ for files specified as CLI args

- bandit/cli/baseline.py
- doc/source/start.rst
- requirements.txt
- setup.cfg
- test-requirements.txt
- tox.ini
The only piece of code that requires GitPython is bandit-baseline. There tends to be an abundance of CVEs in the GitPython library due to its dependency on Git. By making GitPython optional via an extra, users who mostly use just the bandit command line and not bandit-baseline can benefit.
However, this will require different install if a user wants to use bandit-baseline. This is now noted in the Getting Started doc, but you simply do:
```pip install bandit[GitPython]```
FYI, this option was suggested in PR #976.
> Rework GitPython dependency to be an extra for bandit-baseline

- README.rst
A recent change to the README has code blocks in markdown format. Since our README is actually reStructuredText format, this causes syntax errors.
It's even bigger of a problem when an attempt to publish the package with the README serving as the PyPI description. The syntax errors prevents package publishing.
Fixes #1102
> Remove markdown formatting in reStructuredText formatted README

- .github/workflows/build-publish-image.yml
Currently we fail with:
`ERROR: invalid tag "ghcr.io/PyCQA/bandit/bandit:latest": repository name must be lowercase`
This is from the capitalized org name: PyCQA
This change lowercases the entire string
> Downsize the org:repo name

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
PyPI and Test PyPI recently introduced trusted publshing for repositories using GitHub Actions to publish.
Changes having already been made on the PyPI and Test PyPI sites to trust our GitHub actions.
https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
> Utilize PyPI's trusted publishing

- doc/source/conf.py
This is a convenience change to make it so we don't have to update conf.py with the new copyright year every January. Instead, we just use the value from datetime.
> Use datetime to avoid updating copyright year

- bandit/plugins/tarfile_unsafe_members.py
- examples/tarfile_extractall.py
- tests/functional/test_functional.py
Related to issue #1038
Currently the following line: `tarfile.extractall(path=some_path, filter="data")`  raises an error. See comment https://github.com/PyCQA/bandit/issues/1038#issuecomment-1956512283
However, this should be safe according to comment https://github.com/PyCQA/bandit/issues/1038#issuecomment-1834110126
This PR does not attempt to fix issue #1038, but starts by making the line aforementioned legal. If `filter="data"` is detected, the rule is early exited.
cc @mattiasb
Closes: #1025
> filter data is safe for tarfile extractall

- bandit/plugins/injection_shell.py
- examples/subprocess_shell.py
- tests/functional/test_functional.py
`subprocess.getstatusoutput()` will call `check_output(cmd, shell=True)` [source code](https://github.com/python/cpython/blob/22ccf13b332902142fe0c52c593f9efc152c7761/Lib/subprocess.py#L675), so I think extending the scan scope is proper.
> [B605] Add functions that are vulnerable to shell injection.

- bandit/__init__.py
- bandit/formatters/sarif.py
- doc/source/formatters/sarif.rst
- doc/source/man/bandit.rst
- doc/source/start.rst
- setup.cfg
- tests/unit/formatters/test_sarif.py
- tox.ini
This commit adds a formatter that outputs JSON in a specific SARIF format according to spec at [1].
This code is largely leveraged from an existing implementation found here [2].
SARIF format is very useful for integration into ecosystems such as GitHub's Actions.
[1] https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/sarif-v2.1.0-cs01.html
[2] https://github.com/microsoft/bandit-sarif-formatter
Closes #646
> Add a SARIF output formatter

- .github/workflows/pythonpackage.yml
Python 3.13 is currently in alpha, but it's useful to have a test scenario to vet it early before it is released to flush out any Bandit issues as a result of a new runtime.
Note: the Python matrix change here uses a range so that it can continually test 3.13 alpha releases all the way to GA'd versions.
> Start testing on Python 3.13

- .readthedocs.yaml
The doc build nowadays runs via the readthedocs.yaml file. So the requirements for building those docs need to include sarif in order to correctly build the sarif formatter doc.
Fixes: #1138
> Ensure sarif extra is included as part of doc build

- bandit/plugins/injection_shell.py
- examples/subprocess_shell.py
- tests/functional/test_functional.py
Although probably uncommon, it is possible to pass an empty list to one of subprocess functions. If this is done, the injection_shell plugin raises an IndexError while checking the contents of the list argument given.
The fix is to simply check for a non-empty list. Test case was also added.
Fixes: #1141
> Guard against empty call argument list

- bandit/core/context.py
- bandit/formatters/xml.py
- bandit/plugins/injection_wildcard.py
This change makes use of augmented assignment statements as suggested by issue #760.
Fixes: #760`
> Suggested small refactors in assignments

- bandit/blacklists/calls.py
- bandit/core/blacklisting.py
The blacklisting function is currently using fnmatch.fnmatch() to do matching of qualified names of blacklist calls. It seems it is only used for telnetlib and ftplib where they are setting the qualified name in a file glob style (telnetlib.*).
This change would slightly break backward compatibility if there are any third-party plugins that use globbing in the qualified names for blacklisting. I think the likelyhood is small. I also think it is better to be more explicit in the qualified name patterns. In the case of ftplib, FTP is insecure, but FTP_TLS is not. So this already is resolving one false postive.
The other effect of this change is a slight boost to performance. When scanning cpython prior to this fix, it would take around 1 min. After the fix, closer to 50 seconds. So a nice …
> Performance improvement in blacklist function

- bandit/blacklists/calls.py
- bandit/core/blacklisting.py
- examples/ftplib.py
- tests/functional/test_functional.py
This change adds an FTP_TLS call to the examples. A high severity
error is no longer reported as a result of the fix in PR #1148
that explicitly now matches blacklist call qualified names rather
than using a file glob.
However, you will notice that there is one more high severity
issue reported in the tests as a result of the import of
ftplib.FTP_TLS because the blacklist import is only checking for
"ftplib".
Fixes: #148
> Add test for usage of FTP_TLS

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
- .github/workflows/pythonpackage.yml
- .readthedocs.yaml
- bandit/blacklists/calls.py
- bandit/plugins/hashlib_insecure_functions.py
- doc/source/faq.rst
- setup.cfg
- setup.py
- tests/functional/test_functional.py
- tox.ini
As of October 1st, 2024, Python 3.8 becomes end-of-life. As such Bandit should also no longer support the version.
This commit will bump minimum version of support to Python 3.9 and remove any legacy 3.8 specific code.
This is a breaking change for those still using Python 3.8 and so the minor version will be bumped to 1.8.x for it.
Closes #1173
> Removal of Python 3.8 support

- bandit/blacklists/calls.py
- examples/ciphers.py
- tests/functional/test_functional.py
The cryptography project has added a few more cipher algorithms to its list of insecure, out-dated, or deprecated, i.e. decrepit symmetric algorithms.
Namely, CAST5, SEED, and TripleDES were added. As a result, Bandit should also alert to usage of these ciphers.
https://cryptography.io/en/latest/hazmat/decrepit/
> Add more insecure cryptography cipher algorithms

- setup.cfg
The PyPI warehouse supports a number of custom links to display on the project page. Of interest to Bandit are the links to the docs, sponsors, and discord.
https://github.com/pypi/warehouse/blob/main/warehouse/templates/packaging/detail.html
> Update project urls with added links

- README.rst
Sentry recently ended their sponsorship. Technically the sponsorship wasn't going specifically to the project anyway, but to a user (me). So this change updates the README to reflect this.
> Remove Sentry as a sponsor

- .github/ISSUE_TEMPLATE/bug-report.yml
Since Bandit 1.8.0 was just released, the bug template should also have 1.8.0 in its list of choices.
> Update the bug template with latest bandit version

- bandit/blacklists/calls.py
- bandit/blacklists/imports.py
- examples/xml_lxml.py
- tests/functional/test_functional.py
removes B320 (xml_bad_etree) and B410 (import_lxml)
fixes #767
> Remove lxml (B320 & B410) from blacklist

- .github/workflows/pythonpackage.yml
- bandit/core/blacklisting.py
- bandit/core/context.py
- bandit/core/node_visitor.py
- bandit/core/utils.py
- bandit/plugins/django_sql_injection.py
- bandit/plugins/django_xss.py
- bandit/plugins/general_hardcoded_password.py
- bandit/plugins/injection_shell.py
- bandit/plugins/injection_sql.py
- bandit/plugins/tarfile_unsafe_members.py
- tests/unit/core/test_context.py
Reverts PyCQA/bandit#1189
Fixes #1216
> Revert "Start testing with 3.14 alphas"

- .github/ISSUE_TEMPLATE/bug-report.yml
The bug template should include a drop down selection for newly released Bandit versions 1.8.1 and 1.8.2.
> Update bug template to include latest released versions

- bandit/core/context.py
- bandit/plugins/markupsafe_markup_xss.py
- doc/source/plugins/b704_markupsafe_markup_xss.rst
- examples/markupsafe_markup_xss.py
- examples/markupsafe_markup_xss_allowed_calls.py
- examples/markupsafe_markup_xss_extend_markup_names.py
- setup.cfg
- tests/functional/test_functional.py
Closes #1067
This adds a plugin matching the existing Ruff lint [RUF035](https://docs.astral.sh/ruff/rules/unsafe-markup-use/), including its two settings.
> Add markupsafe.Markup XSS plugin

- bandit/core/extension_loader.py
- tests/unit/cli/test_main.py
When a user gives a test ID to include or skip, the current behavior raises an exception and exits the process.
However, when tests end up getting deprecated and eventually removed, it is a lot more user friendly to simple present a warning to the user that the test ID given wasn't found rather than a hard error and exit.
Fixes: #1228, #1226
> Warn not error on an nonexistant test given

- bandit/plugins/general_hardcoded_password.py
- examples/hardcoded-passwords.py
The B107 check was incorrectly flagging None default values as hardcoded passwords in function definitions. This is a false positive since None is a legitimate and commonly used within __init__ initialization
This change modifies the hardcoded_password_default function to:
- Skip None values in parameter defaults
- Handle both ast.Constant (Python 3.8+) and ast.NameConstant (Python 3.7-) representations of None
- Update documentation to clarify None handling behavior
Example of code that no longer triggers B107:
def __init__(self, auth_scheme, auth_password=None):
pass
Fixes: #1227
> B107: Skip None values in hardcoded password detection

- setup.cfg
Not sure if this metadata object changed names over time but some tooling such as LicenseCheck trips up if it's defined as classifier and not classifiers. 
This matches current documentation where it states classifier is an alias of classifiers according to metadata table here: https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#metadata
A separate issue was opened on LicenseCheck.
> Metadata: rename classifier to classifiers

- bandit/core/tester.py
- bandit/plugins/trojansource.py
The trojansource plugin functions differently where it doesn't process a file by AST node. It instead does a line by line search for suspicious characters.
As a result, it can't rely on the linerange being automatically set based on values fetched from the node. So it needs to set the linerange manually.
Fixes: #1246
> Fix traceback from trojansource plugin

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
- setup.py
- tox.ini
Ever since Sphinx switched to sphinx-build command to build docs, the man page was no longer being built. This is because there is now a separate subcommand "sphinx-build -b man" to generate the man page file.
This change adds the separate command and ensures our publish workflows generate the file when releasing a new bandit version.
This also adds the man page as part of the data files so it gets included with the wheel and is installed to share/man/man1.
> Ensure the man page is built

- setup.cfg
When running `tox -e pep8` in the GitHub runner, a warning is displayed noting that the license classifier is deprecated.
```
× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [258 lines of output]
/home/runner/work/bandit/bandit/.tox/pep8/lib/python3.9/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
!!
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: Apache Software License
```
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license
> Use license property in lieu of classifier

- doc/source/index.rst
- doc/source/integrations.rst
New doc to advise users of Bandit of the various integrations available to them. The list is probably missing some, but can be updated with time.
It currently only includes subsections for IDEs, CI/CDs, Linters, and Packages. But that can also be expanded with time.
> Add a doc describing various integrations

- .readthedocs.yaml
Switch from ubuntu 22.04 to latest so we don't have to update this value to the latest version as new releases come out.
> Use ubuntu latest for readthedocs build

- bandit/plugins/general_hardcoded_tmp.py
In the docs for B108, it lists the configurable paths it checks for temp directory-like locations. In addition, it includes a bullet point for "etc". This might be misinterpretted as "/etc". I believe the original intention was to state etcetera, but might be confusing as listed.
This change just removes it from the list to get rid of any potential confusion.
> Remove etc from list of temp paths

- doc/source/ci-cd/index.rst
This change should fix the RST CICD file to properly render.
To see the broken output, look at:
https://bandit.readthedocs.io/en/latest/ci-cd/index.html
> Fix the rendering of the CI/CD doc

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
This change fix the publishing step to PyPI and Test PyPI but ensuring that tox is installed.
This is a new issue to be fixed because previous releases never installed the man page.
Fixes: #1272
> Fix for publish to PyPI failure

- doc/source/integrations.rst
I did not integrate Bandit to FreeBSD, but it is already available there. I'm not a developer/maintainer of the FreeBSD package: [py-bandit](https://www.freshports.org/devel/py-bandit/)
> added hint to FreeBSD package in doc/source/integrations.rst

- CONTRIBUTING.md
This change adds steps to the Contributing document instructions to Maintainers on how to create and publish a release.
This change also fixed some missing steps in the git workflow and update of the Python version used to run unit tests with.
> Add instructions for Maintainers to create/publish a release
