- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
This simple pull adds emoji to the issue types displayed.
> Add emojis to issue types

- bandit/plugins/exec.py
- bandit/plugins/general_bind_all_interfaces.py
Supporting documentation for security risks:
- runtime dynamic execution
- binding sockets to all network interfaces
Fixes #335 
Signed-off-by: Antoine Salon <asalon@vmware.com>
> Add external documentation references

- bandit/core/manager.py
- bandit/formatters/custom.py
Remove support for limiting the number of reports since it is not used anyway.
Closes #371
> Fix custom format argument handling

- doc/source/plugins/b611_django_rawsql_used.rst
The title for 611 has 610. I tried to search and seems to be ok in other places
> Fix B611 doc title

- bandit/formatters/custom.py
- doc/source/formatters/custom.rst
* Add custom.rst to docs source
* Fix custom formatter docstring
Fixes #406
> Add missing custom formatter doc (#406)

- bandit/core/context.py
Fix for issue #448
Code improve
> Fix context class

- bandit/plugins/app_debug.py
> updated readme links for werkzeug debugger

- bandit/core/node_visitor.py
- bandit/core/utils.py
- bandit/plugins/django_xss.py
- bandit/plugins/general_hardcoded_password.py
- bandit/plugins/injection_sql.py
> add namespaces for parent attributes

- README.rst
- bandit/blacklists/calls.py
- bandit/cli/main.py
- bandit/core/constants.py
- bandit/plugins/asserts.py
- bandit/plugins/exec.py
- bandit/plugins/injection_shell.py
- doc/source/man/bandit.rst
> Revert "Revert "Update python documentation links for version 3 counterparts""

- requirements.txt
From #587.
Until the new version of pyyaml is merged, this PR should not be merged. Once the new version is released though, it will be updated here, then it can be merged.
> Bump pyyaml

- setup.cfg
Background info at https://github.com/pypa/warehouse/pull/7882
> Add release notes project URL

- .github/ISSUE_TEMPLATE/config.yml
Prevent the creation of blank issues by adding a config.yml to configure this.  From now on all issues will need to go through either the Bug or Feature Request template.
> Prevent creation of blank issues

- .github/ISSUE_TEMPLATE/bug_report.yaml
Getting syntax error on the steps included in the reproduce section.
> Remove steps in reproduce section

- README.rst
bandit-term.png should be bandit-terminal.png
> Bad link to screen shot

- .github/ISSUE_TEMPLATE/Feature_request.md
This change encourages users to give a 👍 if they really like a particular feature.
> Add request for feedback via 👍

- .github/FUNDING.yml
This change adds myself as a person to sponsor via the GitHub
sponsorship program.
> Add myself to sponsor list

- README.rst
Alert contributors to where on Discord they can reach out for questions and such
> Add Discord link to README

- README.rst
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
> Correct build status badge in README

- .github/ISSUE_TEMPLATE/bug-report.yml
New release, there new version to list in bug report drop down options.
> Update bug report to include version 1.7.5

- .github/ISSUE_TEMPLATE/bug-report.yml
Add the new latest version and default version to the issue template for bugs.
> Add the new release to bandit versions of bug template

- README.rst
This change adds a sponsor section listing out the current sponsors with links to their respective websites.
> Add a sponsor section to README

- .github/ISSUE_TEMPLATE/bug-report.yml
Added 1.7.9 and 1.7.8 to bug template.
> Add recent releases to version choice in bug report

- funding.json
The FLOSS/fund is running a program to invest support in critical, impactful, and valuable open source projects.
Adding this file doesn't guarantee funding, but raises awareness Bandit is seeking it.
The JSON has been validated using their online validation tool: https://dir.floss.fund/validate
More info:
https://floss.fund/blog/announcing-floss-fund/
> Add a JSON to seek funding from the FLOSS/fund

- README.rst
Add Mercedes-Benz to the README as one of our generous sponsors.
> Add Mercedes-Benz to sponsor list

- .github/ISSUE_TEMPLATE/bug-report.yml
Latest version should now be 1.8.3
> Bump bandit version in bug template
